config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  get '/auth/failure', to:redirect('/')
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#show'
  get '/search', to: 'search#index'
  get '/search/:id', to: 'search#show', as: :search_show
  post '/image', to: 'images#create'
  get '/information', to: 'information#index'
  get '/about', to: 'developers#index'
  get '/500', to: 'application#server_errors'
  get '/400', to: 'application#search_errors'
  match 'download', to: 'images#download', as: 'download', via: :get
  get '*path', to: redirect('/404'), constraints: lambda { |req|
  req.path.exclude? 'rails/active_storage' }
  # get '(*url)', to: redirect('/404')
end

app/models/api_image.rb
class ApiImage < ApplicationRecord
  validates :url, presence: true
  validates :source, presence: true

  belongs_to :user

  has_one_attached :original
  has_one_attached :glitched

  def attach_key(key)
    self.key = key
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :url, presence: true
  validates :source, presence: true

  has_one_attached :original
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :uid, uniqueness: true, presence: true

  has_many :api_images, dependent: :destroy

  def self.from_omniauth(params)
    user = find_or_create_by(uid: params[:uid])
    user.name = params[:info][:name]
    user.email = params[:info][:email]
    user.avatar = params[:info][:image]
    user.access_token = params[:credentials][:token]
    user.refresh_token = params[:credentials][:refresh_token]
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end

  private

  def require_user
    render file: '/public/404' if current_user.nil?
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index; end
end

app/controllers/images_controller.rb
require 'securerandom'

class ImagesController < ApplicationController
  before_action :require_user
  include Glitchable
  include S3able

  def create
    api_image = current_user.api_images.create!(image_params)
    download = Down.download(api_image.url)
    api_image.original.attach(io: download, filename: "#{api_image.url}.jpg")
    basic_glitch(api_image)
    api_image.attach_key(upload_image)
    api_image.save
    redirect_to search_show_path(api_image)
  end

  def download
    send_file 'lib/assets/glitched/new_image.png', type: 'image/png', status: 202
  end

  private

  def image_params
    params.permit(:url, :deep_id, :source, :pixabay_id)
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def index; end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :require_user
  def index
    search = params[:search].split.join('+')
    if search.match('[a-zA-Z]+')
      conn = Faraday.get("https://damp-forest-93176.herokuapp.com/images/#{search}")
      get_image_options(conn)
    else
      redirect_to '/400'
    end
  end

  def show
    @api_image = ApiImage.find(params[:id])
  end

  private

  def get_image_options(conn)
    if conn.status == 500
      redirect_to '/500'
    elsif conn.status == 200
      json = JSON.parse(conn.body, symbolize_names: true)
      @image_options = ImageOptions.new(json)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    session[:id] = user.id
    flash[:success] = "Welcome, #{user.name}!"

    redirect_to '/dashboard'
  end

  def destroy
    session.delete(:id) if current_user
    session.delete(:id)
    session[:id] = nil
    redirect_to root_path
    flash[:success] = 'You have successfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  def show
    @user = User.find(current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/developers/index.html.erb
<div class="center-search">
  <h1> Development Team </h1>
</div>

<style>
div.gallery {
  margin: 5px;
  float: left;
  width: 180px;
  border-radius: 50%;
}


div.gallery img {
  width: 100%;
  height: auto;
  border-radius: 50%;
  margin: 0 auto;
}

div.desc {
  padding: 15px;
  text-align: center;
  float: left;
  margin-top: 4em;
}

.center_photo {
  margin: auto;
}

.app-description {
  margin: auto;
}

.about-container {
  display: flex;
  flex-direction: column;
  align-content: center;
  margin-top: 25px;
  margin-bottom: 65px;
  bottom: 10px;
  background-color: #66ffff;
}

</style>

</head>
<body class="text-center text-monospace" style="background-image: url('https://i.imgur.com/Hn8t8ib.jpg'); margin: 0 auto;">
  <div class="container about-container">
    <div class="app-description">
    <br>
      <p>We are the team behind <a href="https://github.com/sciencefixion/glitch_craft">GlitchCraft</a>.
        GlitchCraft is a Ruby on Rails application allowing users to glitch images.
         Users can search for images based off a keyword that will return two images
          for the user's choosing. The first image is created by an AI from scratch
          based on the keyword via DeepAI, while the second is returned based off
          search results from human generated image tags in pixabay. </p>
      <p>The goal of this project was to create a successful Rails application
        from an idea to delivery within 10 days, focused around solving a
        problem or making something creative. Learning goals for us were images, file manipulations, storage solutions and fabulous artwork. All of which were achevied!</p>
      <p> We used an agile process developing our features. Also, Configured a continuous integration server, caching, and implemented a Sinatra Microservice. The tech stack used for this project are the following:</p>
        <p>Ruby on Rails, Active Record, PostgreSQL, Sinatra, Travis CI, Bootstrap, JavaScript, HTML/CSS, and Trello.</p>

    </div>
    <div class="center_photo">
      <div class="gallery center-search">
        <a target="_blank" >
          <img src="https://avatars3.githubusercontent.com/u/37886458?s=460&u=83f7cc97e6e21413954d096159ef462c67513d1e&v=4" alt="Jane Greene" width="600" height="400">
        </a>
        <br>
        <p>Jane Greene</p>
        <a href="https://www.linkedin.com/in/jane-greene-mba/">LinkedIn</a><a> | </a>
        <a href="https://github.com/janegreene">GitHub</a>
      </div>

      <div class="gallery center-search">
        <a target="_blank" >
          <img src= "https://avatars3.githubusercontent.com/u/62079009?s=460&u=ba54507a91cc41193ffa757e661cfc5e708370a7&v=4" alt="Dan Sehl" width="600" height="400">
        </a>
        <br>
        <p>Dan Sehl</p>
        <a href="https://www.linkedin.com/in/danielsehl/">LinkedIn</a><a> | </a>
        <a href="https://github.com/dtsehl">GitHub</a>
      </div>

      <div class="gallery center-search">
        <a target="_blank" >
          <img src="https://avatars1.githubusercontent.com/u/61847658?s=460&u=12c4dff271d79393b5d54867b3d8a73e34286cb1&v=4" alt="Kathy Bui" width="600" height="400">
        </a>
        <br>
        <p>Kathy Bui</p>
        <a href="https://www.linkedin.com/in/kathy-bui-87a27a1ab/">LinkedIn</a><a> | </a>
        <a href="https://github.com/Kathybui732">GitHub</a>
      </div>

      <div class="gallery center-search">
        <a target="_blank" >
          <img src="https://avatars2.githubusercontent.com/u/60492885?s=460&u=a23ddc09c48644913428c412632c5535ce5cb703&v=4" alt="Dorion" width="600" height="400">
        </a>
        <br>
        <p>Rion</p>
        <a href="https://www.linkedin.com/in/rion-h-7b3668b2/">LinkedIn</a><a> | </a>
        <a href="https://github.com/sciencefixion">GitHub</a>
      </div>
    </div>
  </div>
</body>

app/views/information/index.html.erb
<body class="text-center" style="background-image: url('https://image.freepik.com/free-vector/glitched-geometric-shapes-collection_116399-169.jpg'); margin: 0 auto;">
  <center>
    <h1 style="font-family: monaco; margin: 10px; color:white; font-size: 70px;">FAQ</h1>

    <div class="container" style="max-width: 100vw;">
      <div class="card-columns" style="font-family: monaco;">
        <div class="card text-white mb-3" style="max-width: 25rem; height: 100vh; background: rgba(0, 0, 0, 0.8);">
          <div class="card-header"><h5>What is Glitch Art?</h5></div>
          <div class="card-body">
            <p class="card-text">Have you ever accidentally opened a file in the wrong application and panicked? Little did you know you just unlocked a new databending skill! Databending is the process of manipulating a media file of a certain format in a software designed to edit files of another format. Artists have figured out how to percisely manipulate and delicately corrupt data without breaking the file.</p><br>
            <p>Glitch Art is a visual style artform that utilizes databending. It is characteried by using digital and analog errors for asthetic purposes and exposes a medium for expression and creativity in electronic technologies.</p>
          </div>
        </div>
        <div class="card text-white mb-3" style="max-width: 25rem; height: 100vh; background: rgba(0, 0, 0, 0.8);">
          <div class="card-header"><h5>About Our App</h5></div>
          <div class="card-body">
            <p class="card-text">
              Glitch Craft allows you to select an image to glitch from two different sources based off a keyword. The first image is generated fully from scratch based on an AI's preception of the keyword from <a href="https://deepai.org/machine-learning-model/text2img">DeepAI</a>. The second image is found based off human generated perceptions of a keyword through image tags on <a href="https://pixabay.com/">Pixabay</a>. After selecting an image, we'll cause a random glitch to the image's code and yeild your new glitched masterpiece!</p>
          </div>
        </div>
        <div class="card text-white mb-3" style="max-width: 25rem; height: 100vh; background: rgba(0, 0, 0, 0.8);">
          <div class="card-header"><h5>Here are some resources we enjoyed!</h5></div>
          <div class="card-body">
            <p class="card-text">Phillip Stearns has created an extensive <a href="https://phillipstearns.wordpress.com/glitch-art-resources/">resource list</a> for glitch art! Check it out if you want to learn more!</p>

            <p class="card-text">Checkout <a href="https://github.com/osromusic/Glitch-Arts-Resources#galleries">osromusic's repo</a> for a collection of artists and galleries!</p>

            <p class="card-text"><a href="http://www.glitchet.com/resources">Glitchet's art resourses</a> offers a multitude of glitching tutorials utilizing a variety of data file types.</p>
          </div>
        </div>
      </div>
    </div>
  </center>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlitchCraft</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #000000; z-index: 10; background: rgba(0, 0, 0, 0.8); font-family:monaco;">
      <a class="navbar-brand" href="/" style="color:#b3b3b3;">GlitchCraft</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if current_user.nil? %>
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/information">FAQ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/auth/google_oauth2">Login</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/dashboard">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/information">FAQ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/logout" data-method="delete" >Logout</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if !flash.nil? %>
      <% flash.each do |type, message| %>
        <div class="alert alert-danger" role="alert">
          <%= tag.div message %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<body class="text-center embed-responsive-1by1">
  <!-- The video -->
    <video autoplay muted loop id="myVideo">
      <source src="https://i.imgur.com/mlcMvUl.mp4" type="video/mp4">
  </video>

<!-- Optional: some overlay text to describe the video -->
  <div class="content text-monospace text-center embed-responsive-item" style="z-index: 11">
    <h3>select an image to glitch its code</h3>
    <%= button_to "Glitch this Deep AI image", image_path, method: :post, class: "btn btn-dark float-left button-deepai", params: {url: @image_options.deep_url, source: @image_options.deep_source, deep_id: @image_options.deep_id} %>
    <%= button_to "Glitch this Pixabay image", image_path, method: :post, class: "btn btn-dark float-right button-pixabay", params: {url: @image_options.pixabay_url, source: @image_options.pixabay_source, deep_id: @image_options.pixabay_id} %></p>
    <p>the new image will be saved to your profile</p>
    <!-- Use a button to pause/play the video with JavaScript -->
    <button class="myBtn btn-dark" onclick="myFunction()">Pause</button>
  </div>

  <div class="container embed-responsive-1by1">
    <div class="card-columns d-flex justify-content-center" style="margin:25px">
      <div class="card content" style="margin:25px; background: rgba(0, 0, 0, 0.8);">
        <div class="card-block" align="center">
          <h4 class="card-title">Deep AI</h4>
          <img class="image-Deep-AI embed-responsive-item img-fluid" src=<%= @image_options.deep_url %> alt="Deep AI Image" style="max-width:350px; height:350px">

        </div>
      </div>
      <div class="card content" style="margin:25px; background: rgba(0, 0, 0, 0.8);">
        <div class="card-block" align="center">
          <h4 class="card-title">Pixabay</h4>
          <img class="image-Pixabay embed-responsive-item img-fluid" src=<%= @image_options.pixabay_url %> alt="Pixabay Image" style="max-width:350px; height:350px">
        </div>
      </div>
    </div>
  </div>
</body>

<script>
// Get the video
var video = document.getElementById("myVideo");

// Get the button
var btn = document.getElementById("myBtn");

// Pause and play the video, and change the button text
function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>

app/views/search/show.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Add icon library -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body class="text-center">
  <!-- The video -->
  <video autoplay muted loop id="myVideo" style="z-index: -1">
    <source src="https://i.imgur.com/oBG2hmh.mp4" type="video/mp4">
  </video>

  <div class="content">
    <%= link_to 'Download', download_path, target: '_blank', class: "myBtn fa fa-download" %>
    <button class="myBtn fa" onclick="myFunction()">Pause</button>
  </div>

  <center>
    <div class="card embed-responsive-4by3" style="width: 40rem; margin-top: 10px; background: rgba(0, 0, 0, 0.8);">
      <div class="card-body" style="color:#b3b3b3; margin: 10px;">
        <section class="image">
          <%= image_tag "https://#{ENV['AWS_BUCKET']}.s3.amazonaws.com/#{@api_image.key}", :class => "glitched-image embed-responsive-item img-fluid" %>
        </section>
      </div>
    </div>
  </center>

  <!-- <button class="btn"><i class="fa fa-download"></i> Download</button> -->
</body>

<script>
// Get the video
var video = document.getElementById("myVideo");

// Get the button
var btn = document.getElementById("myBtn");

// Pause and play the video, and change the button text
function myFunction() {
  if (video.paused) {
    video.play();
    btn.innerHTML = "Pause";
  } else {
    video.pause();
    btn.innerHTML = "Play";
  }
}
</script>

app/views/users/show.html.erb
<body class="text-center text-monospace" style="background-image: url('https://i.imgur.com/Hn8t8ib.jpg'); margin: 0 auto;">
  <h2 style="margin: 50px"><%= @user.name %>'s dashboard</h1>

  <section class="image-search">
    <p>
      Enter a keyword below and search for an image to glitch!
      <%= form_tag "/search", method: :get do %>
      <%= text_field_tag :search, nil, placeholder: 'keyword', class: 'rounded-pill', style: "background: rgba(0, 0, 0, 0.3);" %>
      <br><br>
      <%= submit_tag "Search", :class => "btn btn-outline-primary" %>
      <% end %>
    </p>
  </section>

  <center>
    <div class="card text-white bg-primary mb-3" style="max-width: 40rem; margin: 50px;">
      <div class="card-header">Don't know what to do?</div>
      <div class="card-body">
        <h5 class="card-title">Instructions:</h5>
        <p class="card-text text-left">
        1. Enter a keyword into the search bar above and hit search.<br><br>
        2. GlitchCraft will render two image options for glitching.<br></p>
        <p class="card-text text-left" style="margin-left: 40px; text-left"><em>Option 1:</em> The DeepAI Image is an AI generated image from scratch based off it's perception of your keyword.<br>
        <em>Option 2:</em> The Pixabay Image is a human tagged image relating to your keyword.<br></p>
        <p class="card-text text-left" style="margin: 20px;">3. Select your image and cause a glitch!<br>
        <br></p>
        NOTE: If you do not like your image selections, simply hit the back button on your browser and create a new search!
      </div>
    </div>
  </center>
</body>

app/views/welcome/index.html.erb
<body class="text-center" style="background-image: url('https://www.webdesignbites.com/wp-content/uploads/2019/04/glitch-art.jpg'); margin: 0 auto;">
  <center>
    <div class="card" style="width: 50rem; margin-top: 130px; background: rgba(0, 0, 0, 0.8); font-family:Monaco;">
      <h1 style="font-size:80px; color:#b3b3b3; margin: 50px 0 50px 0; font-family:Monaco; ">GlitchCraft</h1>
      <div class="card-body" style="color:#b3b3b3; margin: 25px;">
        <p class="card-text description text-monospace">This app allows you to glitch a photo that is created by an AI based on a word or phrase that you provide.</p>
        <p class="card-text text-monospace" style="color:red; margin:25px 0 0 0;">-DISCLAIMER! Pages may include flashing graphics. Proceed with caution-</p>
        <div style="margin: 50px 0 0 0;">
          <% if current_user.nil? %>
          <a href="/auth/google_oauth2" class="btn btn-dark" style="margin: 10px 0 0 0;">Login with Google to Start Glitching</a><br>
          <% end %>
          <a href="/information" class="btn btn-danger" style="margin: 10px 0;">What is Glitch Art?</a>
        </div>
      </div>
    </div>
  </center>
</body>